name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sqlite:
    runs-on: ubuntu-latest
    steps:
    - name: Check sqlite3 version
      run: sqlite3 --version
    - name: Reinstall sqlite3
      run: |
        download_link="https://www.sqlite.org/2023/sqlite-tools-linux-x64-3440200.zip"
        wget "$download_link" -P /tmp
        unzip "/tmp/$(basename "$download_link")" -d /tmp
        sudo install /tmp/sqlite3 /usr/local/bin/
    - name: Check sqlite3 version
      run: sqlite3 --version
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      # set phpunit to false to prevent automatic generation of mysql phpunit jobs
      phpunit: false
      preserve_vendor_tests: true
      extra_jobs: |
        - php: 8.1
          db: sqlite3
          composer_args: --prefer-lowest
          phpunit: true
          phpunit_suite: all
        - php: 8.1
          db: sqlite3
          phpunit: true
          phpunit_suite: all
        - php: 8.2
          db: sqlite3
          phpunit: true
          phpunit_suite: all
